/**
 * Dynamic Data Loader
 *
 * Loads news data from the Horizon → Remotion data bridge output.
 * Falls back to sample data when live data is unavailable.
 *
 * Data source: src/data/remotion-data.json (generated by scripts/data-bridge.py)
 */

import { BroadcastData, NewsItem, sampleBroadcast } from "./data";

interface RemotionDataItem {
  id: string;
  title: string;
  title_zh: string;
  title_en: string;
  summary_zh: string;
  summary_en: string;
  score: number;
  tags: string[];
  category: string;
  source_type: string;
  url: string;
}

interface RemotionDataPackage {
  date: string;
  title: string;
  subtitle: string;
  total_items: number;
  average_score: number;
  news_items: RemotionDataItem[];
  closing_text: string;
  video_config: {
    fps: number;
    width: number;
    height: number;
    opening_duration: number;
    item_duration: number;
    closing_duration: number;
    total_duration: number;
  };
}

// Category color mapping for visual consistency
export const categoryColors: Record<string, string> = {
  top: "#ff6b35",
  tech: "#00b4d8",
  world: "#52b788",
  business: "#ffd700",
  science: "#c77dff",
};

// Category labels
export const categoryLabels: Record<string, string> = {
  top: "头条",
  tech: "科技",
  world: "国际",
  business: "商业",
  science: "科学",
};

/**
 * Parse the category string from JSON data into our NewsItem category type.
 */
function parseCategory(cat: string): NewsItem["category"] {
  const validCategories: NewsItem["category"][] = [
    "top",
    "tech",
    "world",
    "business",
    "science",
  ];
  return validCategories.includes(cat as NewsItem["category"])
    ? (cat as NewsItem["category"])
    : "tech";
}

/**
 * Load broadcast data from the data bridge output.
 *
 * The bridge JSON file is generated by running:
 *   uv run python scripts/data-bridge.py --date 2026-06-11 --lang zh
 */
export async function loadBroadcastData(
  language: string = "zh",
): Promise<BroadcastData> {
  try {
    // In production, this would fetch the JSON from a local file or API.
    // For now, we use a static import approach.
    const data = await import("./data/remotion-data.json") as RemotionDataPackage;

    const items: NewsItem[] = data.news_items.map((item) => ({
      id: item.id,
      title: language === "zh" ? item.title_zh : item.title_en,
      summary: language === "zh" ? item.summary_zh : item.summary_en,
      category: parseCategory(item.category),
      source: `Horizon · ${item.source_type}`,
    }));

    return {
      date: data.date,
      title: data.title,
      subtitle: data.subtitle,
      newsItems: items.slice(0, 6), // Max 6 items for reasonable video length
      closingText: data.closing_text,
    };
  } catch {
    // Fall back to sample data if bridge output is not available
    console.warn(
      "[DataLoader] Bridge data not found. Falling back to sample broadcast data.",
    );
    return sampleBroadcast;
  }
}

/**
 * Get video configuration from the bridge data or use defaults.
 */
export function getVideoConfig(itemCount: number): {
  fps: number;
  width: number;
  height: number;
  openingDuration: number;
  itemDuration: number;
  closingDuration: number;
  totalDuration: number;
} {
  const FPS = 30;
  const OPENING = 90;
  const ITEM = 75;
  const CLOSING = 90;

  return {
    fps: FPS,
    width: 1920,
    height: 1080,
    openingDuration: OPENING,
    itemDuration: ITEM,
    closingDuration: CLOSING,
    totalDuration: OPENING + itemCount * ITEM + CLOSING,
  };
}